networks:
  internal:
volumes:
  - type: volume
    source: config
    target: /ssh
  - type: volume
    source: home
    target: /root
  # - type: bind
  #   source: /backup
  #   target: /backup
  # - type: bind
  #   source: /data
  #   target: /data
  # - type: bind
  #   source: /stack
  #   target: /stack
  # - type: bind
  #   source: /var/run/docker.sock
  #   target: /var/run/docker.sock
