hostname: $STACK_DOMAIN
networks:
  internal:
ports:
  - "22222:22"
volumes:
  - type: volume
    source: config
    target: /ssh
  - type: volume
    source: home
    target: /root
  - type: bind
    source: $STACK_ROOT
    target: $STACK_ROOT
  - type: bind
    source: /var/run/docker.sock
    target: /var/run/docker.sock
