command:
  - "--api=true"
  - "--api.dashboard=true"
  - "--api.insecure=$TRAEFIK_DASHBOARD"
  - "--certificatesresolvers.default.acme.email=hostmaster@$STACK_DOMAIN"
  - "--certificatesresolvers.default.acme.storage=/config/acme.json"
  - "--certificatesresolvers.default.acme.tlschallenge=true"
  - "--entrypoints.http.address=:80"
  - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
  - "--entrypoints.http.http.redirections.entryPoint.to=https"
  - "--entrypoints.https.address=:443"
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--log.level=$TRAEFIK_LOG_LEVEL"
  - "--providers.docker.exposedbydefault=false"
  - "--providers.docker.network=internal"
  - '--providers.docker.defaultrule=Host(`{{ index .Labels "stack.service" }}.{{ index .Labels "stack.domain" }}`)'
  - "--providers.file.filename=/etc/traefik/dynamic.yaml"
extra_hosts:
  - "host.docker.internal:$STACK_HOST_IP"
labels:
  traefik.enable: $TRAEFIK_DASHBOARD
  traefik.http.routers.traefik.rule: Host(`traefik.$STACK_DOMAIN`)
  traefik.http.routers.traefik.entrypoints: https
  traefik.http.routers.traefik.middlewares: secure-headers@file,http-auth
  traefik.http.routers.traefik.tls.certresolver: default
  traefik.http.services.traefik.loadbalancer.server.port: 8080

networks:
  internal:
ports:
  - "80:80"
  - "443:443"
volumes:
  - type: volume
    source: config
    target: /config
  - type: bind
    source: /var/run/docker.sock
    target: /var/run/docker.sock
