depends_on:
  - postgres
networks:
  internal: {}
environment:
  DB_VENDOR: POSTGRES
  DB_ADDR: postgres
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_SCHEMA: public
  DB_DATABASE: keycloak
  PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_LOGLEVEL: INFO
  KEYCLOAK_USER: $KEYCLOAK_USER
  KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
labels:
  traefik.enable: true
  traefik.http.routers.keycloak.rule: Host(`id.$STACK_DOMAIN`)
  traefik.http.routers.keycloak.entrypoints: https
  traefik.http.routers.keycloak.middlewares: secure-headers@file
  traefik.http.routers.keycloak.tls.certresolver: default
  traefik.http.services.keycloak.loadbalancer.server.port: 8080
