depends_on:
  - postgres
environment:
  POSTGRES_DB: nextcloud
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_ADMIN_PASSWORD: password
  NEXTCLOUD_DATA_DIR: /data
  NEXTCLOUD_TRUSTED_DOMAINS: next.$STACK_DOMAIN
  APACHE_DISABLE_REWRITE_IP: "1"
  TRUSTED_PROXIES: $STACK_SUBNET
  OVERWRITEPROTOCOL: https
labels:
  stack.short: next
  traefik.enable: true
  traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent: true
  traefik.http.middlewares.nextcloud-caldav.redirectregex.regex: "^https://(.*)/.well-known/(card|cal)dav"
  traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement: "https://$${1}/remote.php/dav/"
  traefik.http.routers.nextcloud.middlewares: secure-headers,nextcloud-caldav
  traefik.http.routers.nextcloud.tls.certresolver: default
  traefik.http.services.nextcloud.loadbalancer.server.port: 80
networks:
  internal:
volumes:
  - type: volume
    source: html
    target: /var/www/html
  - type: volume
    source: data
    target: /data
