depends_on:
  - postgres
environment:
  POSTGRES_DB: nextcloud
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_ADMIN_PASSWORD: password
  NEXTCLOUD_DATA_DIR: /data
  NEXTCLOUD_TRUSTED_DOMAINS: $STACK_DOMAIN
  TRUSTED_PROXIES: $STACK_SUBNET
  OVERWRITEPROTOCOL: https
labels:
  traefik.enable: true
  traefik.http.routers.nextcloud.rule: Host(`$STACK_DOMAIN`)
  traefik.http.routers.nextcloud.middlewares: nextcloud-caldav
  traefik.http.routers.nextcloud.tls.certresolver: default
  traefik.http.services.nextcloud.loadbalancer.server.port: 80
  traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent: true
  traefik.http.middlewares.nextcloud-caldav.redirectregex.regex: "/.well-known/(card|cal)dav"
  traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement: "/remote.php/dav/"
networks:
  internal:
volumes:
  - type: volume
    source: html
    target: /var/www/html
  - type: volume
    source: data
    target: /data
