environment:
  AUTH_HOST: auth.$STACK_DOMAIN
  COOKIE_DOMAIN: $STACK_DOMAIN
  DEFAULT_PROVIDER: oidc
  PROVIDERS_OIDC_ISSUER_URL: https://id.$STACK_DOMAIN/auth/realms/master
  PROVIDERS_OIDC_CLIENT_ID: $TRAEFIK_OIDC_CLIENT_ID
  PROVIDERS_OIDC_CLIENT_SECRET: $TRAEFIK_OIDC_CLIENT_SECRET
  SECRET: $TRAEFIK_OIDC_SECRET
labels:
  stack.short: auth
  traefik.enable: true
  traefik.http.routers.traefik-auth.tls.certresolver: default
  traefik.http.routers.traefik-auth.middlewares: traefik-auth
  traefik.http.services.traefik-auth.loadbalancer.server.port: 4181
  traefik.http.middlewares.traefik-auth.forwardauth.address: http://traefik-auth:4181
  traefik.http.middlewares.traefik-auth.forwardauth.authResponseHeaders: X-Forwarded-User
networks:
  internal:
