depends_on:
  - postgres
  - http-auth
environment:
  PGADMIN_CONFIG_SERVER_MODE: "False"
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
  PGADMIN_DEFAULT_EMAIL: hostmaster@$STACK_DOMAIN
  PGADMIN_DEFAULT_PASSWORD: password
labels:
  traefik.enable: true
  traefik.http.routers.postgres-admin.rule: Host(`pgadmin.$STACK_DOMAIN`)
  traefik.http.routers.postgres-admin.entrypoints: https
  traefik.http.routers.postgres-admin.middlewares: secure-headers@file,http-auth
  traefik.http.routers.postgres-admin.tls.certresolver: default
  traefik.http.services.postgres-admin.loadbalancer.server.port: 80
networks:
  internal: {}
volumes:
  - type: volume
    source: data
    target: /var/lib/pgadmin
