[http.middlewares]

[http.middlewares.redirect-https.redirectscheme]
scheme = "https"
permanent = true

[http.middlewares.compress.compress]

[http.middlewares.secure-headers.headers]
browserxssfilter = true
contenttypenosniff = true
sslredirect = true
stsincludesubdomains = true
stsseconds = 31536000

[http.middlewares.secure-headers.headers.customrequestheaders]
X-Forwarded-Proto = "https"

[http.middlewares.default.chain]
middlewares = ["secure-headers", "compress"]

[http.routers]

[http.routers.global]
rule = "HostRegexp(`{host:.+}`)"
service = "noop@internal"
entrypoints = ["http"]
middlewares = ["redirect-https"]
priority = 1
